(() => {
  const style=document.createElement('style');
  style.textContent=`
    .pond{display:grid!important;position:relative!important;grid-template-columns:repeat(3,1fr)!important;grid-template-rows:repeat(2,1fr)!important;gap:clamp(12px,2vw,28px)!important;padding:clamp(8px,2vw,18px)!important;align-items:center!important;justify-items:center!important;width:100%!important;margin:0!important;overflow:hidden!important;}
    .spot{position:relative!important;left:auto!important;top:auto!important;right:auto!important;bottom:auto!important;transform:none!important;margin:0!important;justify-self:center!important;align-self:center!important;width:min(264px,28vw)!important;max-width:264px!important;aspect-ratio:1!important;animation:none!important;transition:none!important;}
    .shadow{transition:none!important;}
    .spot:nth-child(1){grid-column:1;grid-row:1}.spot:nth-child(2){grid-column:2;grid-row:1}.spot:nth-child(3){grid-column:3;grid-row:1}.spot:nth-child(4){grid-column:1;grid-row:2}.spot:nth-child(5){grid-column:2;grid-row:2}.spot:nth-child(6){grid-column:3;grid-row:2}
    @media(max-width:700px){.pond{grid-template-columns:repeat(3,1fr)!important;grid-template-rows:repeat(2,1fr)!important;gap:8px!important;padding:4px!important}.spot{width:min(264px,27vw)!important;max-width:145px!important}}
  `;document.head.appendChild(style);
  const gauge=document.getElementById('gauge'),status=document.getElementById('status'),catchBox=document.getElementById('catch'),saveKey='cosmofish-catches',sizeKey='cosmofish-fish-sizes',failKey='cosmofish-failed-catches';
  let sizeRecords={},failedCatches=Number(localStorage.getItem(failKey)||0);try{sizeRecords=JSON.parse(localStorage.getItem(sizeKey)||'{}')}catch(e){}
  const sizeTable=[{name:'特大',rank:5,chance:1},{name:'大',rank:4,chance:9},{name:'中',rank:3,chance:60},{name:'小',rank:2,chance:29.5},{name:'稚魚',rank:1,chance:.5}];
  function pickFishSize(){const x=Math.random()*100;let sum=0;for(const s of sizeTable){sum+=s.chance;if(x<sum)return s}return sizeTable[2]}
  function pickFish(size){const rates=size==='gold'?[['めずらしい',10],['まぼろし',90]]:[['ふつう',91],['めずらしい',9]];let x=Math.random()*100,sum=0;for(const[r,p]of rates){sum+=p;if(x<sum){const a=fishData.filter(f=>f.rarity===r);return a[Math.floor(Math.random()*a.length)]}}}
  function rarityClass(r){return r==='めずらしい'?'rare':r==='まぼろし'?'mythical':'common'}
  function needFor(r){return r==='ふつう'?3:r==='めずらしい'?2:1}
  function saveSize(id,size){const old=sizeRecords[id]||{},previousBest=old.best||null,previousMin=old.min||null,isRecord=size.rank>=2&&(!previousBest||size.rank>previousBest.rank),isMin=!previousMin||size.rank<previousMin.rank,next={best:isRecord?size:previousBest,min:isMin?size:previousMin,latest:size.name};sizeRecords[id]=next;localStorage.setItem(sizeKey,JSON.stringify(sizeRecords));return{isRecord,isMin,previousBest,previousMin}}
  function sizeSpan(label,size){if(!size)return `<div class="size-record">${label}：—</div>`;const cls=size.name==='稚魚'?'fry':size.name==='特大'?'giant':'';return `<div class="size-record ${cls}">${label}：${size.name}</div>`}
  function forceGoldAfterFailureMilestone(){if(failedCatches<10)return;failedCatches=0;localStorage.setItem(failKey,'0');const spots=[...document.querySelectorAll('#pond .spot')];const available=spots.filter(s=>s.querySelector('.shadow'));const target=(available.length?available:spots)[Math.floor(Math.random()*(available.length?available.length:spots.length))];if(target){const old=target.querySelector('.shadow');if(old)old.remove();const gold=document.createElement('div');gold.className='shadow gold';target.appendChild(gold)}status.textContent='金色の魚影が出現した……'}
  gauge.addEventListener('pointerdown',(e)=>{if(!active)return;e.preventDefault();e.stopImmediatePropagation();const barPosition=pos,targetLeft=40,targetRight=60;active=false;cancelAnimationFrame(raf);if(barPosition>=targetLeft&&barPosition<=targetRight){const f=pickFish(currentSize);if(!f){status.textContent='魚影の解析に失敗しました';return}const previousCount=counts[f.id]||0,caughtSize=pickFishSize(),record=saveSize(f.id,caughtSize);if(currentSize==='gold'){failedCatches=0;localStorage.setItem(failKey,'0')}counts[f.id]=previousCount+1;localStorage.setItem(saveKey,JSON.stringify(counts));const need=needFor(f.rarity),isNew=previousCount===0,isAnalysisComplete=previousCount<need&&counts[f.id]>=need;let labels='';if(isNew)labels+='<div class="catch-label new-species">新種捕獲</div>';if(isAnalysisComplete)labels+='<div class="catch-label analysis-complete">解析完了</div>';if(caughtSize.name==='稚魚')labels+='<div class="catch-label fry">稚魚</div>';else if(record.isRecord)labels+='<div class="catch-label new-record">新記録</div>';const rarityClassName=rarityClass(f.rarity);labels+='<div class="catch-success">捕獲成功！</div><div class="catch-fish-name '+rarityClassName+'"><span class="catch-rarity '+rarityClassName+'">'+f.rarity+'</span><span>'+f.name+'</span></div><div class="catch-size">サイズ：'+caughtSize.name+'</div><button type="button" class="catch-recover">回収</button>';catchBox.innerHTML=labels;catchBox.classList.remove('hidden');status.classList.add('success');status.textContent='捕獲しました（'+counts[f.id]+'回目）';const recover=catchBox.querySelector('.catch-recover');if(recover)recover.addEventListener('click',(ev)=>{ev.preventDefault();ev.stopPropagation();catchBox.classList.add('hidden');status.classList.remove('success');status.textContent='魚影をタップして釣りを開始';shadows()})}else{failedCatches++;localStorage.setItem(failKey,String(failedCatches));if(failedCatches>=10)forceGoldAfterFailureMilestone();else status.textContent='逃げられた……'}},{capture:true});
  window.shadows=function(){const spots=[...document.querySelectorAll('#pond .spot')];if(!spots.length)return;spots.forEach(s=>{s.style.opacity='1';if(!s.querySelector('.shadow')){const el=document.createElement('div'),r=Math.random();el.className='shadow '+(r<.0005?'gold':r<.09?'large':'medium');el.style.opacity='1';s.appendChild(el)}})};
  document.addEventListener('pointerdown',(e)=>{const s=e.target.closest('.shadow');if(!s||active)return;e.preventDefault();e.stopImmediatePropagation();active=true;currentSize=s.classList.contains('gold')?'gold':s.classList.contains('large')?'large':'medium';const direction=Math.random()<0.5?1:-1;pos=direction===1?0:100;cursor.style.left=pos+'%';status.textContent=direction===1?'ゲージ：→':'ゲージ：←';gaugeStart=performance.now();function move(now){if(!active)return;const elapsed=(now-gaugeStart)%1000;pos=direction===1?(elapsed<500?(elapsed/500)*100:(1-(elapsed-500)/500)*100):(elapsed<500?100-(elapsed/500)*100:(elapsed-500)/500*100);cursor.style.left=pos+'%';raf=requestAnimationFrame(move)}raf=requestAnimationFrame(move)},{capture:true});
  const originalShowDetail=window.showDetail;if(originalShowDetail)window.showDetail=function(f,count,need){originalShowDetail(f,count,need);const desc=document.getElementById('dd');let sizeEl=document.getElementById('detailSize');if(!sizeEl){sizeEl=document.createElement('div');sizeEl.id='detailSize';sizeEl.className='detail-size';desc.parentNode.insertBefore(sizeEl,desc)}const rec=sizeRecords[f.id];sizeEl.innerHTML=rec?sizeSpan('最大',rec.best)+sizeSpan('最小',rec.min):sizeSpan('最大',null)+sizeSpan('最小',null)};
  const originalRender=window.render;if(originalRender)window.render=function(){originalRender();document.querySelectorAll('#list .card').forEach(card=>{[...card.children].filter(el=>el.textContent.trim().startsWith('最大')).forEach(el=>el.remove());const no=card.querySelector('.no');if(!no)return;const m=no.textContent.match(/No\.(\d+)/);if(!m)return;const id=Number(m[1]),rec=sizeRecords[id];if(!rec)return;const el=document.createElement('div');el.className='size-records';el.style.marginTop='6px';el.innerHTML=sizeSpan('最大',rec.best)+sizeSpan('最小',rec.min);card.appendChild(el)})};
})();